version: "3.11"

services:
  app:
    container_name: blog-django
    build: .
    command: python3 ./my_blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: blog-postgres
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres_data:
